import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.css";
import { GlobalProvider } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cyrus Technology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <GlobalProvider>
      <body className={inter.className}>{children}</body>
      </GlobalProvider>
    </html>
  );
}
